apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demo-app
data:
  nginx.conf: |
    server {
      listen 80;
      server_name app.onumanozdemir.online;

      root /app/public;  # Symfony'nin public dizinine işaret ediyor
      index index.php index.html index.htm;

      location / {
          try_files $uri /index.php$is_args$args;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_pass 127.0.0.1:9000;
          fastcgi_param SCRIPT_FILENAME /app/public$fastcgi_script_name;
          include fastcgi_params;
      }

      error_log  /var/log/nginx/error.log;
      access_log /var/log/nginx/access.log;
    }
